### ISSUE TITLE
[Bug]: Attribute points cannot be returned

### ISSUE THREAD

**Issue by luoxiawuchen** [promcteam/proskillapi#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

2、The attribute point cannot be returned by right clicking in the menu (even if it is allowed to be returned in config, from the error log, this error seems to be related to vault. The vault version I use is 1.7.3)

### Expected Behavior

2、Ability to return attribute points

### Steps To Reproduce

1、Turn on the server

2、Install promcore, proskillapi, proskillapiparties

3、The above error occurred

### Environment

```markdown
- Server Software: PaperSpigot 1.16.5
- ProSkillAPI Version: proskillapi-1.1.7.15-0930442
- ProMCCore Version: promccore-1.0.3.7-0930442
- Plugins:proskillapi-1.1.7.15-0930442、promccore-1.0.3.7-0930442、ProSkillAPIParties-1.0-snapshot、Vault-1.7.3、EssentialsX-2.19.4
```

### latest.log

https://pastebin.com/AxxbrwAw

**Comment by lordsrubka5** [comment]
I have the same issue doe vault but my atrributes are fine. Is your formula correct? Can you show it?

**Comment by luoxiawuchen** [comment]
> 我对金库有同样的问题，但我的atrributes很好。您的公式是否正确？你能展示出来吗？

Thank you for your concern and reply.
I think it should not be a formula problem, because I use the default configuration of the plugin.
This is really strange.

The following configuration are the attributes

vitality: 
  display: 'Vitality'
  max: '999'
  icon: 'ink sack'
  icon-data: '1'
  icon-lore: 
  - '&6Vitality &7(&2{amount}&7)'
  - ''
  - '&7Grants 1 health per'
  - '&7point invested.'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    health: 'a+v'

**Comment by luoxiawuchen** [comment]
> I have the same issue for vault but my atrributes are fine. Is your formula correct? Can you show it?

Sorry, I made a mistake. The invalid attribute is not the problem of proskill API. I made a mistake in my profession at the beginning of configuration. Strangely, I did fail to use the default configuration before, and now the retest is effective again (maybe it's my own operation problem, it's really strange)

**Comment by BijuuKrunos** [comment]
I got the same issue and i dont see an issue with my attributes file. Vault is installed aswell. Please fix this bug my players cant undo there points!!

**Comment by BijuuKrunos** [comment]
mhh I even cant use the /class refund command, I get the message that my points are resetted but they aren't.

**Comment by SparkGNRK** [comment]
Do you have also an economy plugin installed with vault? (like EssentialsX for example)

**Comment by luoxiawuchen** [comment]
> Do you have also an economy plugin installed with vault? (like EssentialsX for example)

Thank you for reminding me. Indeed, I ignored the problem of installing essx. Another error will appear after installation, and the AP cannot be undo. It is still related to vaulthook

[20:49:56 ERROR]: Could not pass event InventoryClickEvent to ProSkillAPI v1.1.7.15
java.lang.NullPointerException: null
        at com.sucy.skill.hook.VaultHook.getBalance(VaultHook.java:133) ~[?:?]
        at com.sucy.skill.hook.VaultHook.hasBalance(VaultHook.java:137) ~[?:?]
        at com.sucy.skill.gui.handlers.AttributeHandler.onClick(AttributeHandler.java:59) ~[?:?]
        at com.sucy.skill.gui.handlers.AttributeHandler.onClick(AttributeHandler.java:36) ~[?:?]
        at com.sucy.skill.gui.tool.GUIHolder.handleClick(GUIHolder.java:100) ~[?:?]
        at com.sucy.skill.listener.ToolListener.onClick(ToolListener.java:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by lordsrubka5** [comment]
Economy works fine. Its just that for me at least when the server is started up the hook for vault is weird. I can't remember if it hooks in the startup or says that it failed (I mentioned it on discord before) but when trying to right click to downgrade attributes it says

[20:52:10 ERROR]: Could not pass event InventoryClickEvent to ProSkillAPI v1.1.7.16
java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer, String)" because "com.sucy.skill.hook.VaultHook.economy" is null

However when I change the price of downgrade to for example 1 it works. It also works when I change it back to 0

**Comment by SparkGNRK** [comment]
I think I found where the error come from, I will do a pull request when I have time to fix it. Thanks for reporting the error!

**Comment by luoxiawuchen** [comment]
> I think I found where the error come from, I will do a pull request when I have time to fix it. Thanks for reporting the error!

Well,thank you for your patience and contribution to plugin maintenance

**Comment by Travja** [comment]
Sorry for the delay on this. This should be resolved in the latest versions of ProSkillAPI

**Comment by luoxiawuchen** [comment]
> 很抱歉耽误了时间。这应该在最新版本的 ProSkillAPI 中解决

Oddly enough, this problem still exists in the latest proskill API

[12:57:40 ERROR]: Could not pass event InventoryClickEvent to ProSkillAPI v1.1.7.16
java.lang.NullPointerException: null
        at com.sucy.skill.hook.VaultHook.getBalance(VaultHook.java:133) ~[?:?]
        at com.sucy.skill.hook.VaultHook.hasBalance(VaultHook.java:137) ~[?:?]
        at com.sucy.skill.gui.handlers.AttributeHandler.onClick(AttributeHandler.java:59) ~[?:?]
        at com.sucy.skill.gui.handlers.AttributeHandler.onClick(AttributeHandler.java:36) ~[?:?]
        at com.sucy.skill.gui.tool.GUIHolder.handleClick(GUIHolder.java:100) ~[?:?]
        at com.sucy.skill.listener.ToolListener.onClick(ToolListener.java:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by Travja** [comment]
> > 很抱歉耽误了时间。这应该在最新版本的 ProSkillAPI 中解决
> 
> 
> 
> Oddly enough, this problem still exists in the latest proskill API
> 
> 
> 
> [12:57:40 ERROR]: Could not pass event InventoryClickEvent to ProSkillAPI v1.1.7.16
> 
> java.lang.NullPointerException: null
> 
>         at com.sucy.skill.hook.VaultHook.getBalance(VaultHook.java:133)

Could you try with x.17 available on Discord?

**Comment by luoxiawuchen** [comment]
> > > 很抱歉耽误了时间。这应该在最新版本的 ProSkillAPI 中解决
> > 
> > 
> > 奇怪的是，这个问题仍然存在于最新的proskill API中。
> > [12：57：40 错误]： 无法将事件“清单”单击“事件”事件“图标发送到 ProSkillAPI v1.1.7.16
> > java.lang.NullPointerException： null
> > ```
> >     at com.sucy.skill.hook.VaultHook.getBalance(VaultHook.java:133)
> > ```
> 
> 你能尝试在Discord上使用x.17吗？

Oh, OK, thank you. I'll have a try

**Comment by luoxiawuchen** [comment]
> > > 很抱歉耽误了时间。这应该在最新版本的 ProSkillAPI 中解决
> > 
> > 
> > 奇怪的是，这个问题仍然存在于最新的proskill API中。
> > [12：57：40 错误]： 无法将事件“清单”单击“事件”事件“图标发送到 ProSkillAPI v1.1.7.16
> > java.lang.NullPointerException： null
> > ```
> >     at com.sucy.skill.hook.VaultHook.getBalance(VaultHook.java:133)
> > ```
> 
> 你能尝试在Discord上使用x.17吗？

It has been repaired. Thank you for your patience
