### ISSUE TITLE
[Bug]: MySQL sync issues

### ISSUE THREAD

**Issue by ReverseAllen** [promcteam/proskillapi#363]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Start MySQL save mode In BungeeCord Server.
Data can be lost in many cases.
After repeated testing up to hundreds of times.

1. If player connects to the server when the server is shut down, his data will be completely lost.
2. When the server is whitelisted, players trying to log in to the server will cause complete data loss.
If periodic saving is turned on, the same problem will occur.
3. If periodic saving is turned on, when players move across servers that synchronize data, have small chance data will be completely lost.

### Expected Behavior

Hope to add a way to save to solve the problem.
Or add a regular data retrospective function, which can easily help players recover lost data.

### Steps To Reproduce

Start MySQL save mode In BungeeCord Server.
Data can be lost in many cases.
After repeated testing up to hundreds of times.

1. If player connects to the server when the server is shut down, his data will be completely lost.
Simple test method: lobby server -> test server
2. When the server is whitelisted, players trying to log in to the server will cause complete data loss.
Simple test method: lobby server -> test server
If periodic saving is turned on, the same problem will occur.
3. If periodic saving is turned on, when players move across servers that synchronize data, have small chance data will be completely lost.
Simple test method: test1 server (use proskillapi server) -> test2 server (use proskillapi server)

### Environment

```markdown
- Server Software: PaperSpigot 1.16.5
- ProSkillAPI Version: 1.1.7.16-1330
- ProMCCore Version: 1.0.3.8-1150257
- Plugins: Essentials, Itemizer, Vault, TabList, Core, PlaceholderAPI, CMILib, GroupManager, ProMCCore, Multiverse-Core, LibsDisguises, InventorySaver, BetterGUI, Vulcan, Residence, MythicMobs, Citizens, ProSkillAPI, ProtocolLib
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

If the delayed loading of data is not enabled, If player try to restart the server without completely restarting the server. When logging in, it will cause the plugin to load the data abnormally, and then cause the server to crash without responding.

**Comment by Travja** [comment]
I'm a bit confused here. Are you installing ProSkillAPI on the Bungee instance? The SQL implementation does need work, but if you're installing on Bungee and trying to sync without an online server to join, I'm not sure that this would actually function as you intend.

**Comment by ReverseAllen** [comment]
> I'm a bit confused here. Are you installing ProSkillAPI on the Bungee instance? The SQL implementation does need work, but if you're installing on Bungee and trying to sync without an online server to join, I'm not sure that this would actually function as you intend.

I installed proskillapi on the subserver under Bungee.
And enable MySQL to store player data.
problems described above all occur when proskillapi is installed on the sub-server to synchronize data.
Synchronized data is often lost accidentally.

**Comment by ReverseAllen** [comment]
Detailed descriptions of certain parts.

1. When the server is closed, there will be a period of time to execute the shutdown. During that time, the player can still try to connect to the server. If the player tries to connect, it will cause data loss.

2. After the server has been running for a long time.
Then execute the normal shutdown command, and after restarting the server, sometimes it is found that some player's data is accidentally lost.
It's unclear why.

**Comment by Travja** [comment]
@ReverseAllen Sorry this has been so long. I'm not convinced the code I just pushed will fix this. More particularly, it may fix the server-closing issue. Probably not the random data loss on shutdown. Feel free to give the new build a try though and let me know.

**Comment by ReverseAllen** [comment]
When the server is whitelisted, players trying to log in to the server will cause complete data loss.
This problem still exists.
@Travja

**Comment by Travja** [comment]
Ah! @ReverseAllen huge! That's a solid way to reproduce this! Thank you!

**Comment by ReverseAllen** [comment]
> Ah! @ReverseAllen huge! That's a solid way to reproduce this! Thank you!

A clearer way to test and reproduce.
Should be whitelist enable server.
Players who are not included in the whitelist will be blocked from entering.
Then if the player tries to connect and log in, all data will be lost.

**Comment by lordsrubka5** [comment]
D9es it matter what whitelist it is? Defaukt minecraft one or plugin based

**Comment by ReverseAllen** [comment]
> 

Whitelist for Minecraft itself.
How to reproduce:
1. player is't in whitelist
2. The player connects to the server that starts the whitelist.
3. data loser

**Comment by ReverseAllen** [comment]
> 

Supplement: This method is when the server restarts
When the plug-in is unloading or loading, the problem is triggered by the player performing related operations.

**Comment by ReverseAllen** [comment]
Currently using the latest development version
The problem of user data loss continues to occur.
After shutting down the server normally and restarting it, it is always found that some user data is inexplicably lost.
There are also attempts to let the players log out of the server first, then shut down the server and restart it, but data loss still occurs.

**Comment by Travja** [comment]
So **someone** always gets their data wiped when the server restarts? Are they getting kicked back to a hub server (and does the hub have SkillAPI installed)? or just disconnected? If it's not their entire player data, what all is lost?

**Comment by ReverseAllen** [comment]
close server error.
what is this problem?

[11:57:02 ERROR]: Error occurred while disabling ProSkillAPI v1.1.8-R0.10-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.sucy.skill.api.player.PlayerAccounts.getPlayer()" because "data" is null
        at com.sucy.skill.data.io.IOManager.save(IOManager.java:356) ~[?:?]
        at com.sucy.skill.data.io.SQLIO.saveSingle(SQLIO.java:133) ~[?:?]
        at com.sucy.skill.data.io.SQLIO.saveAll(SQLIO.java:116) ~[?:?]
        at com.sucy.skill.SkillAPI.onDisable(SkillAPI.java:593) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:906) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1182) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by ReverseAllen** [comment]
In the case of using MySQL storage mode.

The autosave problem still causes player data to be lost unexpectedly.
When a player transfers across servers on a sub-server with proskillapi installed, there is a chance that the data will be completely lost.

Maybe the problem is that the auto-save process is also in progress when the player crosses servers, causing some kind of read conflict.

The easiest way to restore is to set the auto-save time to a very low value, and then repeatedly perform cross-server transfers between the two servers to reproduce the problem.

**Comment by tangjin0418** [comment]
I've just found where the problem is:
  1. The data was saved, but the `InventoryCloseEvent` fired.
  2. The data was loaded again.
  3. The data will be kept in this server, and anything will be rollbacked if the data is saved.

Some tests:
![image](https://user-images.githubusercontent.com/55261514/217321437-ec526db7-46ae-471a-940a-0b0073ba2f17.png)
![image](https://user-images.githubusercontent.com/55261514/217321483-b792a87b-53d3-4806-b301-b5bb15fa765f.png)

**Comment by Travja** [comment]
Oh interesting. I'll have to do some digging and verifying that so I can see what I can do. Thanks for your sharp eye!

**Comment by Travja** [comment]
Wait so what are you saying needs to be changed then?

**Comment by tangjin0418** [comment]
Add an early-return statement for checking isn't `ALLOWED`.

**Comment by Travja** [comment]
Oh I see, you were showing modified code, not the code at present. If you want to just create a PR, that would be a great help!

**Comment by tangjin0418** [comment]
Sorry I have about zero experience with GitHub.
Please do that 4 me, thanks a lot.

**Comment by tangjin0418** [comment]
Hello @Travja, I just lead you to the wrong way to fix the "whitelist" error,
sorry about that.

It seems like login result will always be `ALLOWED` in Async<ins>_Pre_</ins>LoginEvent

So, the modified correct code should be:
![image](https://user-images.githubusercontent.com/55261514/219851216-dfc73f0a-0614-49d2-b872-593d9dbe8b8f.png)
